/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as IndexRouteImport } from './index'
import { Route as RulesetIndexRouteImport } from './ruleset/index'
import { Route as LogIndexRouteImport } from './log/index'
import { Route as InboundIndexRouteImport } from './inbound/index'
import { Route as ExperimentalIndexRouteImport } from './experimental/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesetIndexRoute = RulesetIndexRouteImport.update({
  id: '/ruleset/',
  path: '/ruleset/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogIndexRoute = LogIndexRouteImport.update({
  id: '/log/',
  path: '/log/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboundIndexRoute = InboundIndexRouteImport.update({
  id: '/inbound/',
  path: '/inbound/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentalIndexRoute = ExperimentalIndexRouteImport.update({
  id: '/experimental/',
  path: '/experimental/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experimental': typeof ExperimentalIndexRoute
  '/inbound': typeof InboundIndexRoute
  '/log': typeof LogIndexRoute
  '/ruleset': typeof RulesetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experimental': typeof ExperimentalIndexRoute
  '/inbound': typeof InboundIndexRoute
  '/log': typeof LogIndexRoute
  '/ruleset': typeof RulesetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experimental/': typeof ExperimentalIndexRoute
  '/inbound/': typeof InboundIndexRoute
  '/log/': typeof LogIndexRoute
  '/ruleset/': typeof RulesetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/experimental' | '/inbound' | '/log' | '/ruleset'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/experimental' | '/inbound' | '/log' | '/ruleset'
  id: '__root__' | '/' | '/experimental/' | '/inbound/' | '/log/' | '/ruleset/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperimentalIndexRoute: typeof ExperimentalIndexRoute
  InboundIndexRoute: typeof InboundIndexRoute
  LogIndexRoute: typeof LogIndexRoute
  RulesetIndexRoute: typeof RulesetIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruleset/': {
      id: '/ruleset/'
      path: '/ruleset'
      fullPath: '/ruleset'
      preLoaderRoute: typeof RulesetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log/': {
      id: '/log/'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbound/': {
      id: '/inbound/'
      path: '/inbound'
      fullPath: '/inbound'
      preLoaderRoute: typeof InboundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experimental/': {
      id: '/experimental/'
      path: '/experimental'
      fullPath: '/experimental'
      preLoaderRoute: typeof ExperimentalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperimentalIndexRoute: ExperimentalIndexRoute,
  InboundIndexRoute: InboundIndexRoute,
  LogIndexRoute: LogIndexRoute,
  RulesetIndexRoute: RulesetIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
