/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as IndexRouteImport } from './index'
import { Route as RulesetIndexRouteImport } from './ruleset/index'
import { Route as LogIndexRouteImport } from './log/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesetIndexRoute = RulesetIndexRouteImport.update({
  id: '/ruleset/',
  path: '/ruleset/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogIndexRoute = LogIndexRouteImport.update({
  id: '/log/',
  path: '/log/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/log': typeof LogIndexRoute
  '/ruleset': typeof RulesetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/log': typeof LogIndexRoute
  '/ruleset': typeof RulesetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/log/': typeof LogIndexRoute
  '/ruleset/': typeof RulesetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/log' | '/ruleset'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/log' | '/ruleset'
  id: '__root__' | '/' | '/log/' | '/ruleset/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogIndexRoute: typeof LogIndexRoute
  RulesetIndexRoute: typeof RulesetIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruleset/': {
      id: '/ruleset/'
      path: '/ruleset'
      fullPath: '/ruleset'
      preLoaderRoute: typeof RulesetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log/': {
      id: '/log/'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogIndexRoute: LogIndexRoute,
  RulesetIndexRoute: RulesetIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
