/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as IndexRouteImport } from './index'
import { Route as SubscribeIndexRouteImport } from './subscribe/index'
import { Route as RulesetIndexRouteImport } from './ruleset/index'
import { Route as LogIndexRouteImport } from './log/index'
import { Route as InboundIndexRouteImport } from './inbound/index'
import { Route as ExperimentalIndexRouteImport } from './experimental/index'
import { Route as DnsIndexRouteImport } from './dns/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeIndexRoute = SubscribeIndexRouteImport.update({
  id: '/subscribe/',
  path: '/subscribe/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesetIndexRoute = RulesetIndexRouteImport.update({
  id: '/ruleset/',
  path: '/ruleset/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogIndexRoute = LogIndexRouteImport.update({
  id: '/log/',
  path: '/log/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboundIndexRoute = InboundIndexRouteImport.update({
  id: '/inbound/',
  path: '/inbound/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentalIndexRoute = ExperimentalIndexRouteImport.update({
  id: '/experimental/',
  path: '/experimental/',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsIndexRoute = DnsIndexRouteImport.update({
  id: '/dns/',
  path: '/dns/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dns': typeof DnsIndexRoute
  '/experimental': typeof ExperimentalIndexRoute
  '/inbound': typeof InboundIndexRoute
  '/log': typeof LogIndexRoute
  '/ruleset': typeof RulesetIndexRoute
  '/subscribe': typeof SubscribeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dns': typeof DnsIndexRoute
  '/experimental': typeof ExperimentalIndexRoute
  '/inbound': typeof InboundIndexRoute
  '/log': typeof LogIndexRoute
  '/ruleset': typeof RulesetIndexRoute
  '/subscribe': typeof SubscribeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dns/': typeof DnsIndexRoute
  '/experimental/': typeof ExperimentalIndexRoute
  '/inbound/': typeof InboundIndexRoute
  '/log/': typeof LogIndexRoute
  '/ruleset/': typeof RulesetIndexRoute
  '/subscribe/': typeof SubscribeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dns'
    | '/experimental'
    | '/inbound'
    | '/log'
    | '/ruleset'
    | '/subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dns'
    | '/experimental'
    | '/inbound'
    | '/log'
    | '/ruleset'
    | '/subscribe'
  id:
    | '__root__'
    | '/'
    | '/dns/'
    | '/experimental/'
    | '/inbound/'
    | '/log/'
    | '/ruleset/'
    | '/subscribe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DnsIndexRoute: typeof DnsIndexRoute
  ExperimentalIndexRoute: typeof ExperimentalIndexRoute
  InboundIndexRoute: typeof InboundIndexRoute
  LogIndexRoute: typeof LogIndexRoute
  RulesetIndexRoute: typeof RulesetIndexRoute
  SubscribeIndexRoute: typeof SubscribeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe/': {
      id: '/subscribe/'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruleset/': {
      id: '/ruleset/'
      path: '/ruleset'
      fullPath: '/ruleset'
      preLoaderRoute: typeof RulesetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log/': {
      id: '/log/'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbound/': {
      id: '/inbound/'
      path: '/inbound'
      fullPath: '/inbound'
      preLoaderRoute: typeof InboundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experimental/': {
      id: '/experimental/'
      path: '/experimental'
      fullPath: '/experimental'
      preLoaderRoute: typeof ExperimentalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns/': {
      id: '/dns/'
      path: '/dns'
      fullPath: '/dns'
      preLoaderRoute: typeof DnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DnsIndexRoute: DnsIndexRoute,
  ExperimentalIndexRoute: ExperimentalIndexRoute,
  InboundIndexRoute: InboundIndexRoute,
  LogIndexRoute: LogIndexRoute,
  RulesetIndexRoute: RulesetIndexRoute,
  SubscribeIndexRoute: SubscribeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
